name: Nasa CI

on:
  push:
    branches: ["nasa"]
  pull_request:
    branches: ["nasa"]

jobs:
  build:
    env:
      CI: true #for cra on client
      MONGO_URL: mongodb://localhost/nasa
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        mongodb-version: [6.x]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Nodejs v${{matrix.node-version}}
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}
      
      - name: MongoDB in GitHub Actions
        uses: supercharge/mongodb-github-action@1.9.0
        with:
          mongodb-version: ${{matrix.mongodb-version}}

      - run: npm install
      - run: npm run build --prefix client
      - run: npm test
